/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Metro;
import classes.Onibus;
import classes.Trem;
import classes.Veiculo;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import operacoes.CadastroVeiculoOperacao;

/**
 *
 * @author barbara
 */
public class CadastroVeiculo extends javax.swing.JFrame {

    private ArrayList<Veiculo> veiculos;
    private Veiculo veiculo;

    /**
     * Creates new form CadastroVeiculo
     */
    public CadastroVeiculo(ArrayList<Veiculo> veiculos, Veiculo veiculo) {
        this.veiculos = veiculos;
        this.veiculo = veiculo;

        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        if (veiculo != null) {
            this.carregarDados();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAcessível = new javax.swing.ButtonGroup();
        hLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bCadastrar = new javax.swing.JButton();
        bFechar = new javax.swing.JButton();
        lCapacidade = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        sCapacidade = new javax.swing.JSpinner();
        lAcessivel = new javax.swing.JLabel();
        rbSim = new javax.swing.JRadioButton();
        rbNao = new javax.swing.JRadioButton();
        lNumSeguro = new javax.swing.JLabel();
        tNumSeguro = new javax.swing.JTextField();
        lDataAquisicao = new javax.swing.JLabel();
        lRegioes = new javax.swing.JLabel();
        tRegioes = new javax.swing.JTextField();
        lBairro = new javax.swing.JLabel();
        tBairro = new javax.swing.JTextField();
        lPlaca = new javax.swing.JLabel();
        tPlaca = new javax.swing.JTextField();
        lModelo = new javax.swing.JLabel();
        tModelo = new javax.swing.JTextField();
        lIntegracao = new javax.swing.JLabel();
        tIntegracao = new javax.swing.JTextField();
        tdataAquisicao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Transporte");

        hLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/assinando (1).png"))); // NOI18N
        hLabel.setText("Cadastro de Veículos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        bCadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NovoConfirmar.png"))); // NOI18N
        bCadastrar.setText("Cadastrar");
        bCadastrar.setToolTipText("");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        bFechar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/multiply (1).png"))); // NOI18N
        bFechar.setText("Fechar");
        bFechar.setToolTipText("");
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });

        lCapacidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lCapacidade.setText("Capacidade:");

        lTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Metrô", "Ônibus", "Trem" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        lAcessivel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lAcessivel.setText("Acessível:");

        bgAcessível.add(rbSim);
        rbSim.setText("Sim");

        bgAcessível.add(rbNao);
        rbNao.setText("Não");

        lNumSeguro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNumSeguro.setText("Número do Seguro:");

        lDataAquisicao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lDataAquisicao.setText("Data Aquisição:");

        lRegioes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lRegioes.setText("Regiões:");

        tRegioes.setEnabled(false);

        lBairro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lBairro.setText("Bairros:");

        tBairro.setEnabled(false);

        lPlaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPlaca.setText("Placa:");

        tPlaca.setEnabled(false);

        lModelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lModelo.setText("Modelo:");

        tModelo.setEnabled(false);

        lIntegracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lIntegracao.setText("Integrações:");

        try {
            tdataAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lAcessivel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbSim)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbNao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lNumSeguro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tNumSeguro))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lTipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lDataAquisicao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tdataAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lCapacidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lIntegracao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tIntegracao))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lRegioes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tRegioes, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lBairro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tBairro))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lPlaca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lModelo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tModelo))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDataAquisicao)
                    .addComponent(tdataAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCapacidade)
                    .addComponent(sCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lAcessivel)
                        .addComponent(rbSim)
                        .addComponent(rbNao)
                        .addComponent(lNumSeguro))
                    .addComponent(tNumSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIntegracao)
                    .addComponent(tIntegracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRegioes)
                    .addComponent(tRegioes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBairro)
                    .addComponent(tBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lModelo)
                        .addComponent(tModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lPlaca)
                        .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(hLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        String tipo = (String) this.cbTipo.getSelectedItem();
        String acessivel = this.rbSim.isSelected() ? "Sim" : this.rbNao.isSelected() ? "Não" : "Não informado";
        String numSeguro = this.tNumSeguro.getText();
        String integracao = this.tIntegracao.getText();
        String regioes = this.tRegioes.getText();
        int capacidade = Integer.parseInt(this.sCapacidade.getValue().toString());
        String bairros = this.tBairro.getText();
        String modelo = this.tModelo.getText();
        String placa = this.tPlaca.getText();
        String data = this.tdataAquisicao.getText();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        if (veiculo == null) {
            try {
                CadastroVeiculoOperacao.cadastroVeiculo(this.veiculos, data, capacidade, numSeguro, integracao, regioes, bairros, tipo, modelo, placa, acessivel);
            } catch (ParseException ex) {
                Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.veiculo.setTipo(tipo);
            this.veiculo.setSeguro(numSeguro);
            this.veiculo.setAcessibilidade(acessivel);
            try {
                this.veiculo.setAquisicao(formatter.parse(data));
            } catch (ParseException ex) {
                Logger.getLogger(CadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.veiculo.setIntegracao(integracao);
            if (this.veiculo.getTipo().toLowerCase().equals("metrô")) {
                Metro metro = (Metro) veiculo;
                metro.setBairros(bairros);
            } else if (this.veiculo.getTipo().toLowerCase().equals("ônibus")) {
                Onibus onibus = (Onibus) veiculo;
                onibus.setModelo(modelo);
                onibus.setPlaca(placa);
            } else if (this.veiculo.getTipo().toLowerCase().equals("trem")) {
                Trem trem = (Trem) veiculo;
                trem.setRegiao(regioes);
            }
            JOptionPane.showConfirmDialog(null, "Dados Atualizados com Sucesso!", "Sucesso!", JOptionPane.DEFAULT_OPTION);
        }
        this.dispose();
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_bFecharActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        if (cbTipo.getSelectedItem().toString().equals("Metrô")) {
            this.tRegioes.setEnabled(false);
            this.tBairro.setEnabled(true);
            this.tPlaca.setEnabled(false);
            this.tModelo.setEnabled(false);
        } else if (cbTipo.getSelectedItem().toString().equals("Trem")) {
            this.tRegioes.setEnabled(true);
            this.tBairro.setEnabled(false);
            this.tPlaca.setEnabled(false);
            this.tModelo.setEnabled(false);
        } else {
            this.tRegioes.setEnabled(false);
            this.tBairro.setEnabled(false);
            this.tPlaca.setEnabled(true);
            this.tModelo.setEnabled(true);
        }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void carregarDados() {
        Date dataAquisicao = veiculo.getAquisicao();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String data = dateFormat.format(dataAquisicao);

        cbTipo.setSelectedItem(this.veiculo.getTipo());
        tdataAquisicao.setText(data);
        sCapacidade.setValue(this.veiculo.getCapacidade());
        rbSim.setSelected(veiculo.getAcessibilidade().equals("Sim"));
        rbNao.setSelected(veiculo.getAcessibilidade().equals("Não"));
        tNumSeguro.setText(this.veiculo.getSeguro());
        tIntegracao.setText(this.veiculo.getIntegracao());
        if (this.veiculo.getTipo().toLowerCase().equals("metrô")) {
            Metro metro = (Metro) veiculo;
            tBairro.setText(metro.getBairros());
        } else if (this.veiculo.getTipo().toLowerCase().equals("ônibus")) {
            Onibus onibus = (Onibus) veiculo;
            tPlaca.setText(onibus.getPlaca());
            tModelo.setText(onibus.getModelo());
        } else if (this.veiculo.getTipo().toLowerCase().equals("trem")) {
            Trem trem = (Trem) veiculo;
            tRegioes.setText(trem.getRegiao());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bFechar;
    private javax.swing.ButtonGroup bgAcessível;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel hLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lAcessivel;
    private javax.swing.JLabel lBairro;
    private javax.swing.JLabel lCapacidade;
    private javax.swing.JLabel lDataAquisicao;
    private javax.swing.JLabel lIntegracao;
    private javax.swing.JLabel lModelo;
    private javax.swing.JLabel lNumSeguro;
    private javax.swing.JLabel lPlaca;
    private javax.swing.JLabel lRegioes;
    private javax.swing.JLabel lTipo;
    private javax.swing.JRadioButton rbNao;
    private javax.swing.JRadioButton rbSim;
    private javax.swing.JSpinner sCapacidade;
    private javax.swing.JTextField tBairro;
    private javax.swing.JTextField tIntegracao;
    private javax.swing.JTextField tModelo;
    private javax.swing.JTextField tNumSeguro;
    private javax.swing.JTextField tPlaca;
    private javax.swing.JTextField tRegioes;
    private javax.swing.JFormattedTextField tdataAquisicao;
    // End of variables declaration//GEN-END:variables
}
